"""
Element Scaffolding Engine for debim.
Generates consistent Pydantic models, resolver logic, QTO formulas, and unit test skeletons
for new BIM element classes.
"""

from pathlib import Path
from typing import Dict, Optional


def snake_case(name: str) -> str:
    """Convert PascalCase (e.g. IfcRailing) to snake_case (e.g. ifc_railing)."""
    import re
    s = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s).lower()


def generate_scaffold_artifacts(
    class_name: str,
    placement_type: str = "grid",
    layer: Optional[str] = None,
) -> Dict[str, str]:
    """
    Generate code snippets and test skeletons for scaffolding a new element class.

    Returns a dict with keys:
    - schema_code: Pydantic model for schema.py
    - resolver_code: Resolved class & SpatialResolver method for resolver.py
    - qto_code: QTO extraction function snippet for qto.py
    - test_code: Pytest test suite for tests/test_<element_name>.py
    """
    if not class_name.startswith("Ifc"):
        class_name = f"Ifc{class_name[0].upper()}{class_name[1:]}"

    elem_name_snake = snake_case(class_name)
    raw_name = class_name[3:] if class_name.startswith("Ifc") else class_name
    default_layer = layer or f"architecture/{raw_name.lower()}s"

    # 1. Schema model generator
    schema_code = f'''class {class_name}Placement(BaseModel):
    grid: Optional[Tuple[str, str]] = None
    storey: str
    offset_x: float = 0.00
    offset_y: float = 0.00
    offset_z: float = 0.00


class {class_name}(BaseModel):
    class_: Literal["{class_name}"] = Field(alias="class", default="{class_name}")
    tag: str
    material: str
    placement: {class_name}Placement
    layer: Optional[str] = "{default_layer}"
'''

    # 2. Resolver code generator
    resolver_code = f'''class Resolved{raw_name}(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    tag: str
    element: {class_name}
    position: Tuple[float, float, float]
    layer: str = "{default_layer}"


def resolve_{elem_name_snake}(self, elem: {class_name}) -> Resolved{raw_name}:
    storey = self.get_storey(elem.placement.storey)
    if elem.placement.grid:
        gx, gy = self.get_grid_xy(elem.placement.grid)
        pos = (gx + elem.placement.offset_x, gy + elem.placement.offset_y, storey.elevation + elem.placement.offset_z)
    else:
        pos = (elem.placement.offset_x, elem.placement.offset_y, storey.elevation + elem.placement.offset_z)
    return Resolved{raw_name}(
        tag=elem.tag,
        element=elem,
        position=pos,
        layer=derive_default_layer(elem),
    )
'''

    # 3. QTO extraction snippet
    qto_code = f'''elif isinstance(resolved, Resolved{raw_name}):
    elem = resolved.element
    return ElementQTO(
        tag=resolved.tag,
        element_class=elem.class_,
        material=elem.material,
        concrete_volume=0.0,
        formwork_area=0.0,
        rebar_weights={{}},
        total_rebar_weight=0.0,
    )
'''

    # 4. Pytest test skeleton
    test_code = f'''"""
Automated unit test skeleton for {class_name} element class.
Generated by debim scaffold CLI.
"""

from debim.schema import {class_name}, {class_name}Placement
from debim.resolver import SpatialResolver, ProjectManifest, Storey, SpatialStructure, Grids, ProjectInfo


def test_{elem_name_snake}_instantiation():
    elem = {class_name}(
        tag="{raw_name.upper()}-01",
        material="Steel",
        placement={class_name}Placement(
            grid=("1", "A"),
            storey="L1",
        ),
        layer="{default_layer}",
    )
    assert elem.tag == "{raw_name.upper()}-01"
    assert elem.class_ == "{class_name}"
    assert elem.layer == "{default_layer}"


def test_{elem_name_snake}_resolution():
    manifest = ProjectManifest(
        project=ProjectInfo(id="PRJ-TEST", name="Test Project"),
        spatial_structure=SpatialStructure(
            storeys=[Storey(id="L1", name="Level 1", elevation=0.0, height=3.5)]
        ),
        grids=Grids(axes_x={{"1": 0.0}}, axes_y={{"A": 0.0}}),
        materials=[{{"id": "Steel", "name": "Steel", "category": "Steel", "unit_cost_ref": "REF"}}],
        elements=[
            {class_name}(
                tag="{raw_name.upper()}-01",
                material="Steel",
                placement={class_name}Placement(
                    grid=("1", "A"),
                    storey="L1",
                ),
            )
        ],
    )
    resolver = SpatialResolver(manifest)
    res = resolver.resolve()
    assert len(res.elements) == 1
    assert res.elements[0].tag == "{raw_name.upper()}-01"
'''

    return {
        "schema_code": schema_code,
        "resolver_code": resolver_code,
        "qto_code": qto_code,
        "test_code": test_code,
    }


def scaffold_element(
    class_name: str,
    placement_type: str = "grid",
    layer: Optional[str] = None,
    dry_run: bool = True,
    output_dir: Optional[Path] = None,
) -> Dict[str, str]:
    """
    Scaffold a new element class. If dry_run is True, returns generated snippets.
    If dry_run is False and output_dir is given, writes generated test and artifact files.
    """
    artifacts = generate_scaffold_artifacts(class_name, placement_type, layer)

    if not dry_run and output_dir:
        output_dir.mkdir(parents=True, exist_ok=True)
        elem_snake = snake_case(class_name)

        (output_dir / f"{elem_snake}_schema.py").write_text(artifacts["schema_code"], encoding="utf-8")
        (output_dir / f"{elem_snake}_resolver.py").write_text(artifacts["resolver_code"], encoding="utf-8")
        (output_dir / f"{elem_snake}_qto.py").write_text(artifacts["qto_code"], encoding="utf-8")
        (output_dir / f"test_{elem_snake}.py").write_text(artifacts["test_code"], encoding="utf-8")

    return artifacts
